/*
Oura API Documentation

Testing EnhancedTagRoutesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oura

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_oura_EnhancedTagRoutesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EnhancedTagRoutesAPIService MultipleEnhancedTagDocumentsV2UsercollectionEnhancedTagGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnhancedTagRoutesAPI.MultipleEnhancedTagDocumentsV2UsercollectionEnhancedTagGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedTagRoutesAPIService SingleEnhancedTagDocumentV2UsercollectionEnhancedTagDocumentIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var documentId string

		resp, httpRes, err := apiClient.EnhancedTagRoutesAPI.SingleEnhancedTagDocumentV2UsercollectionEnhancedTagDocumentIdGet(context.Background(), documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
