/*
Oura API Documentation

Testing DailyReadinessRoutesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oura

import (
	"context"
	"testing"

	openapiclient "github.com/jjenkins/oura"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_oura_DailyReadinessRoutesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DailyReadinessRoutesAPIService MultipleDailyReadinessDocumentsV2UsercollectionDailyReadinessGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DailyReadinessRoutesAPI.MultipleDailyReadinessDocumentsV2UsercollectionDailyReadinessGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DailyReadinessRoutesAPIService SingleDailyReadinessDocumentV2UsercollectionDailyReadinessDocumentIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var documentId string

		resp, httpRes, err := apiClient.DailyReadinessRoutesAPI.SingleDailyReadinessDocumentV2UsercollectionDailyReadinessDocumentIdGet(context.Background(), documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
