/*
Oura API Documentation

Testing DailyActivityRoutesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oura

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_oura_DailyActivityRoutesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DailyActivityRoutesAPIService MultipleDailyActivityDocumentsV2UsercollectionDailyActivityGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DailyActivityRoutesAPI.MultipleDailyActivityDocumentsV2UsercollectionDailyActivityGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DailyActivityRoutesAPIService SingleDailyActivityDocumentV2UsercollectionDailyActivityDocumentIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var documentId string

		resp, httpRes, err := apiClient.DailyActivityRoutesAPI.SingleDailyActivityDocumentV2UsercollectionDailyActivityDocumentIdGet(context.Background(), documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
