/*
Oura API Documentation

Testing RingConfigurationRoutesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oura

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_oura_RingConfigurationRoutesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RingConfigurationRoutesAPIService MultipleRingConfigurationDocumentsV2UsercollectionRingConfigurationGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RingConfigurationRoutesAPI.MultipleRingConfigurationDocumentsV2UsercollectionRingConfigurationGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RingConfigurationRoutesAPIService SingleRingConfigurationDocumentV2UsercollectionRingConfigurationDocumentIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var documentId string

		resp, httpRes, err := apiClient.RingConfigurationRoutesAPI.SingleRingConfigurationDocumentV2UsercollectionRingConfigurationDocumentIdGet(context.Background(), documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
