/*
Oura API Documentation

Testing DailyResilienceRoutesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oura

import (
	"context"
	"testing"

	openapiclient "github.com/jjenkins/oura"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_oura_DailyResilienceRoutesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DailyResilienceRoutesAPIService MultipleDailyResilienceDocumentsV2UsercollectionDailyResilienceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DailyResilienceRoutesAPI.MultipleDailyResilienceDocumentsV2UsercollectionDailyResilienceGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DailyResilienceRoutesAPIService SingleDailyResilienceDocumentV2UsercollectionDailyResilienceDocumentIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var documentId string

		resp, httpRes, err := apiClient.DailyResilienceRoutesAPI.SingleDailyResilienceDocumentV2UsercollectionDailyResilienceDocumentIdGet(context.Background(), documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
