/*
Oura API Documentation

Testing DailyStressRoutesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oura

import (
	"context"
	"testing"

	openapiclient "github.com/jjenkins/oura"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_oura_DailyStressRoutesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DailyStressRoutesAPIService MultipleDailyStressDocumentsV2UsercollectionDailyStressGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DailyStressRoutesAPI.MultipleDailyStressDocumentsV2UsercollectionDailyStressGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DailyStressRoutesAPIService SingleDailyStressDocumentV2UsercollectionDailyStressDocumentIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var documentId string

		resp, httpRes, err := apiClient.DailyStressRoutesAPI.SingleDailyStressDocumentV2UsercollectionDailyStressDocumentIdGet(context.Background(), documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
